/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto.so;

import clases.PCB;
import clases.Planificador;
import clases.GeneradorProcesos; // Importante para el botón aleatorio
import javax.swing.JOptionPane;
/**
 *
 * @author Home
 */
public class PanelCreador extends javax.swing.JPanel {

    private Planificador planificadorRef;
    
    /**
     * Creates new form PanelCreador
     */
    public PanelCreador() {
        initComponents();
    }
    
    public void setPlanificador(Planificador planif) {
        this.planificadorRef = planif;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnManual = new javax.swing.JButton();
        btnAleatorio = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        spnInstrucciones = new javax.swing.JSpinner();
        spnTamano = new javax.swing.JSpinner();
        spnPrioridad = new javax.swing.JSpinner();

        jLabel1.setText("Nombre:");

        jLabel2.setText("Instrucciones:");

        jLabel3.setText("Tamaño (MB):");

        jLabel4.setText("Prioridad:");

        btnManual.setText("Crear (Manual)");
        btnManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManualActionPerformed(evt);
            }
        });

        btnAleatorio.setText("Crear Aleatorio");
        btnAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAleatorioActionPerformed(evt);
            }
        });

        spnInstrucciones.setModel(new javax.swing.SpinnerNumberModel(10, 1, null, 1));

        spnTamano.setModel(new javax.swing.SpinnerNumberModel(10, 1, null, 1));

        spnPrioridad.setModel(new javax.swing.SpinnerNumberModel(10, 1, null, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnTamano, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAleatorio)
                    .addComponent(btnManual))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(spnInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnManual))
                            .addGap(5, 5, 5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(spnTamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAleatorio)
                                .addComponent(jLabel3)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(spnPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManualActionPerformed
        // TODO add your handling code here:
        if (planificadorRef == null) return;
        
        try{
            // 1. Obtener datos de los campos
            String nombre = txtNombre.getText();
            int instruc = (int) spnInstrucciones.getValue();
            int tamano = (int) spnTamano.getValue();
            int prioridad = (int) spnPrioridad.getValue();
            
            // Validaciones básicas
            if(nombre.isEmpty()){
                JOptionPane.showMessageDialog(this, "Ponle nombre al proceso");
                return;
            }
            if (instruc <= 0 || tamano <= 0){
                JOptionPane.showMessageDialog(this, "Valores deben ser positivos");
                return;
            }
            
            // 2. Crear el PCB
            // (Ajusta los parámetros según tu constructor real de PCB)
            // Constructor: (nombre, totalInstr, prioridad, deadline, cicloIO, duracionIO, tamano)
            int deadline = instruc * 2; // Un deadline estimado
            PCB nuevo = new PCB(nombre, instruc, prioridad, deadline, 0, 0, tamano);
            
            // 3. Enviarlo al planificador
            boolean exito = planificadorRef.agregarProceso(nuevo);
            
            if (exito){
                JOptionPane.showMessageDialog(this, "Proceso creado!");
                txtNombre.setText(""); // Limpiar campo
            
            } else{
                JOptionPane.showMessageDialog(this, "Error: Memoria llena o cola llena.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en los datos: " + e.getMessage());
        }
    }//GEN-LAST:event_btnManualActionPerformed

    private void btnAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAleatorioActionPerformed
        // TODO add your handling code here:
        if (planificadorRef == null) return;
        
        // Usamos la clase GeneradorProcesos que ya tienen en el proyecto
        PCB nuevo = GeneradorProcesos.generarProcesoAleatorio();
        
        boolean exito = planificadorRef.agregarProceso(nuevo);
        
        if (exito) {
            // Opcional: Mostrar en consola o un mensajito rápido
            System.out.println("Proceso Aleatorio Creado: " + nuevo.getNombre());
        } else{
            JOptionPane.showMessageDialog(this, "No se pudo crear (Memoria Llena)");
        }
    }//GEN-LAST:event_btnAleatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAleatorio;
    private javax.swing.JButton btnManual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner spnInstrucciones;
    private javax.swing.JSpinner spnPrioridad;
    private javax.swing.JSpinner spnTamano;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
