/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto.so;

import clases.Memoria;
import clases.PCB;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
/**
 *
 * @author Home
 */
public class PanelMemoria extends javax.swing.JPanel {
    
    // Método llamado por el Timer principal
    public void actualizarMemoria(Memoria memoria) {
        // 1. Obtener datos del Backend
        PCB[] particiones = memoria.getParticiones(); // Necesitas haber creado este getter en Memoria.java
        int memLibre = memoria.getMemoriaDisponible();
        int memTotal = 1024; // Valor fijo según tu enunciado (o pásalo como variable)
        int memOcupada = memTotal - memLibre;
        
        // 2. Actualizar Labels y Barra
        lblEstado.setText("Uso: " + memOcupada + " MB / " + memTotal + " MB");
        
        // Si pusiste la barra de progreso:
        if (barraMemoria != null) {
            int porcentaje = (memOcupada * 100) / memTotal;
            barraMemoria.setValue(porcentaje);
            
            // Un toque de color: Rojo si está muy llena, Verde si está bien
            if (porcentaje > 80) {
                barraMemoria.setForeground(Color.RED);
            } else {
                barraMemoria.setForeground(Color.GREEN);
            }
        }

        // 3. Llenar la Tabla
        DefaultTableModel modelo = (DefaultTableModel) tbMemoria.getModel();
        modelo.setRowCount(0); // Limpiar tabla anterior
        
        for (int i = 0; i < particiones.length; i++) {
            if (particiones[i] != null) {
                // --- CASO: SLOT OCUPADO ---
                PCB p = particiones[i];
                modelo.addRow(new Object[]{
                    "Bloque " + i,
                    p.getId(),
                    p.getNombre(),
                    p.getTamano() + " MB",
                    "OCUPADO"
                });
            } else {
                // --- CASO: SLOT LIBRE ---
                modelo.addRow(new Object[]{
                    "Bloque " + i,
                    "---",
                    "---",
                    "---",
                    "LIBRE"
                });
            }
        }
    }

    /**
     * Creates new form PanelMemoria
     */
    public PanelMemoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMemoria = new javax.swing.JTable();
        barraMemoria = new javax.swing.JProgressBar();

        jLabel1.setText("MEMORIA PRINCIPAL (RAM)");

        lblEstado.setText("Memoria Disponible: ??? (MB)");

        tbMemoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Particion", "PID", "Proceso", "Tamano", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tbMemoria);

        barraMemoria.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lblEstado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(barraMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblEstado)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(barraMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraMemoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JTable tbMemoria;
    // End of variables declaration//GEN-END:variables
}
