/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto.so;
import clases.PCB;
import clases.Planificador;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Home
 */
public class PanelColas extends javax.swing.JPanel {
    
    private Planificador planificadorRef; // Referencia para agregar procesos

    /**
     * Creates new form PanelColas
     */
    public PanelColas() {
        initComponents();
    }
    
    public void setPlanificador(Planificador planificador) {
        this.planificadorRef = planificador;
    }
    
    // Este método será llamado por el Timer de la ventana principal cada segundo
    public void actualizarColas(estructuras.ColaPrioridad<PCB> colaListos, estructuras.ListaEnlazada<PCB> listaBloq) {
        
        // --- 1. PINTAR TABLA DE LISTOS ---
        DefaultTableModel modeloListos = (DefaultTableModel) tbListos.getModel();
        modeloListos.setRowCount(0); // Limpiar tabla vieja
        
        // Usamos tu método toArray()
        Object[] arrayListos = colaListos.toArray();
        
        for (Object obj : arrayListos) {
            if (obj != null) {
                PCB p = (PCB) obj; // Casting de Object a PCB
                modeloListos.addRow(new Object[]{
                    p.getId(),
                    p.getNombre(),
                    p.getPrioridad(),
                    p.getTamano() + " MB"
                });
            }
        }
        
        // --- 2. PINTAR TABLA DE BLOQUEADOS ---
        DefaultTableModel modeloBloq = (DefaultTableModel) tbBloqueados.getModel();
        modeloBloq.setRowCount(0); // Limpiar tabla vieja
        
        Object[] arrayBloq = listaBloq.toArray();
        
        for (Object obj : arrayBloq) {
            if (obj != null) {
                PCB p = (PCB) obj;
                modeloBloq.addRow(new Object[]{
                    p.getId(),
                    p.getNombre(),
                    "I/O", // Motivo
                    p.getContadorIO() // Ciclos que lleva esperando
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbBloqueados = new javax.swing.JTable();

        jLabel1.setText("COLA DE LISTOS (Ready)");

        jLabel2.setText("COLA DE BLOQUEADOS (Waiting)");

        tbListos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Prioridad", "Tamano"
            }
        ));
        jScrollPane1.setViewportView(tbListos);

        tbBloqueados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Motivo", "Tiempo Restante"
            }
        ));
        jScrollPane2.setViewportView(tbBloqueados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbBloqueados;
    private javax.swing.JTable tbListos;
    // End of variables declaration//GEN-END:variables
}
